# Generated by Django 3.2.8 on 2021-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barghash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='Barghash/static/Barghash/images'),
        ),
    ]
