# Generated by Django 3.2.8 on 2021-11-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barghash', '0005_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='numper_of_posts',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
